### ISSUE TITLE
cannot import name 'Qwen2_5VLForConditionalGeneration' from 'transformers'

### ISSUE THREAD

**Issue by lshigami** [QwenLM/Qwen2.5-VL#1385]
I get this error

`ImportError: cannot import name 'Qwen2_5VLForConditionalGeneration' from 'transformers' (/pipeline/.venv/lib/python3.10/site-packages/transformers/__init__.py)`

"transformers==4.54.1"

**Comment by ronnief1** [comment]
should work with transformers==4.55.0. but the import should be Qwen2_5_VLForConditionalGeneration
